# -*- coding: utf-8 -*-
"""RAG_Yout_Tube_ChatBot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s9Jjd-9ex9Z-BovsTjcnxronLdI4AorA
"""

import os

# Set Gemini API Key
os.environ["GOOGLE_API_KEY"] = "AIzaSyAF8g_pO2a-3G4seRlFy9UmsAvMXVUfEAQ"

"""1. INDEXING A. DATA **INTERGRATION**"""

!pip install -U langchain langchain-google-genai google-generativeai faiss-cpu

from langchain_community.llms import HuggingFacePipeline
from transformers import pipeline

hf_pipeline = pipeline(
    "text2text-generation",
    model="google/flan-t5-base",
    max_new_tokens=256
)

llm = HuggingFacePipeline(pipeline=hf_pipeline)

!pip install -U langchain-community

!pip install -U youtube-transcript-api

from langchain_community.document_loaders import YoutubeLoader

video_url = "https://www.youtube.com/watch?v=wIFABvwm1wY"

loader = YoutubeLoader.from_youtube_url(
    video_url,
    add_video_info=False
)

documents = loader.load()

len(documents)

"""1.B. DATA **CHUNKING**"""

!pip install -U langchain langchain-core

!pip install -U langchain-text-splitters

from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200
)

chunks = text_splitter.split_documents(documents)

len(chunks)

"""1.C.**ENBEDDINGS**"""

from langchain_community.embeddings import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

from langchain_community.vectorstores import FAISS

vectorstore = FAISS.from_documents(
    chunks,
    embedding=embeddings
)

"""2. **RETRIEVER**"""

retriever = vectorstore.as_retriever(
    search_type="similarity",
    search_kwargs={"k": 8}
)

query = "What is this video about?"
docs = retriever.invoke(query)
len(docs)

"""3.4.AUGMENTATION + **GENERATION**"""

from langchain_core.prompts import PromptTemplate

prompt = PromptTemplate(
    input_variables=["context", "question"],
    template="""
You are a helpful assistant.

Use ONLY the information from the context below to answer.
If the answer is not present in the context, say:
"Answer not found in the video."

Give a clear and detailed answer.

Context:
{context}

Question:
{question}

Answer:
"""
)

qa_chain = prompt | llm

question = """
Explain in detail what this video is about.
Include the main ideas, techniques discussed, and the purpose of the video.
"""

docs = retriever.invoke(question)

# build full context (NO slicing)
context = "\n\n".join(doc.page_content for doc in docs)

response = qa_chain.invoke(
    {
        "context": context,
        "question": question
    }
)

print("ANSWER:\n")
print(response)

print("\n\nSOURCES USED:\n")
for i, doc in enumerate(docs, 1):
    print(f"Source {i}:\n{doc.page_content[:300]}...\n")

"""**STREAMLITE**"""

!pip install streamlit

!pip install -U langchain langchain-community langchain-core

!pip install -q streamlit pyngrok langchain langchain-community langchain-core
!pip install -q langchain-text-splitters youtube-transcript-api
!pip install -q faiss-cpu transformers sentence-transformers

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import os
# import streamlit as st
# 
# from langchain_community.document_loaders import YoutubeLoader
# from langchain_text_splitters import RecursiveCharacterTextSplitter
# from langchain_community.embeddings import HuggingFaceEmbeddings
# from langchain_community.vectorstores import FAISS
# from langchain_community.llms import HuggingFacePipeline
# from transformers import pipeline
# from langchain_core.prompts import PromptTemplate
# 
# st.set_page_config(page_title="YouTube RAG Chatbot", layout="wide")
# st.title("📺 YouTube Video Q&A (RAG)")
# 
# @st.cache_resource
# def load_llm():
#     hf_pipeline = pipeline(
#         "text2text-generation",
#         model="google/flan-t5-base",
#         max_new_tokens=256
#     )
#     return HuggingFacePipeline(pipeline=hf_pipeline)
# 
# @st.cache_resource
# def build_vectorstore(video_url):
#     loader = YoutubeLoader.from_youtube_url(video_url, add_video_info=False)
#     documents = loader.load()
# 
#     splitter = RecursiveCharacterTextSplitter(
#         chunk_size=1000,
#         chunk_overlap=200
#     )
#     chunks = splitter.split_documents(documents)
# 
#     embeddings = HuggingFaceEmbeddings(
#         model_name="sentence-transformers/all-MiniLM-L6-v2"
#     )
# 
#     return FAISS.from_documents(chunks, embeddings)
# 
# video_url = st.text_input("🔗 Enter YouTube URL")
# question = st.text_area(
#     "❓ Ask a question",
#     "Explain in detail what this video is about."
# )
# 
# if st.button("Get Answer"):
#     if not video_url:
#         st.warning("Please enter a URL")
#         st.stop()
# 
#     with st.spinner("Processing video..."):
#         llm = load_llm()
#         vectorstore = build_vectorstore(video_url)
#         retriever = vectorstore.as_retriever(search_kwargs={"k": 8})
# 
#         docs = retriever.invoke(question)
#         context = "\n\n".join(doc.page_content for doc in docs)
# 
#         prompt = PromptTemplate(
#             input_variables=["context", "question"],
#             template="""
# Use ONLY the information from the context below.
# If not found, say "Answer not found in the video."
# 
# Context:
# {context}
# 
# Question:
# {question}
# 
# Answer:
# """
#         )
# 
#         qa_chain = prompt | llm
#         response = qa_chain.invoke({
#             "context": context,
#             "question": question
#         })
# 
#     st.subheader("✅ Answer")
#     st.write(response)
# 
#     st.subheader("📌 Sources")
#     for i, doc in enumerate(docs, 1):
#         st.write(f"Source {i}: {doc.page_content[:300]}...")
#

!streamlit run app.py &>/content/logs.txt &

from pyngrok import ngrok

ngrok.set_auth_token("384emBn9nTC0aituPsQjLxV1Kox_6nMYwYqrQj8EQLn2vegXS")

public_url = ngrok.connect(8501)
public_url

